import { type SearchUser } from "./types";

export const MOCK_USERS: SearchUser[] = [
    {
        id: "user-1",
        name: "EldenLord_VN",
        username: "@eldenlord",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=EldenLord",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=EldenLord",
        bio: "Tarnished warrior exploring the Lands Between. Hardcore Souls player.",
        status: "online",
        isOnline: true,
        game: "ELDEN RING",
        favoriteGame: "ELDEN RING",
        badge: "PRO GAMER",
        isFriend: false,
    },
    {
        id: "user-2",
        name: "ShadowHunter",
        username: "@shadowhunter",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ShadowHunter",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=ShadowHunter",
        bio: "Tactical FPS specialist & competitive strategist. Apex & CS2 veteran.",
        status: "in-game",
        isOnline: true,
        game: "Cyberpunk 2077",
        favoriteGame: "Cyberpunk 2077",
        badge: "VERIFIED",
        isFriend: true,
    },
    {
        id: "user-3",
        name: "ValkyrieQueen",
        username: "@valkyrie",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Valkyrie",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Valkyrie",
        bio: "God of War speedrunner & community guide creator.",
        status: "offline",
        isOnline: false,
        game: "God of War Ragnarök",
        favoriteGame: "God of War Ragnarök",
        isFriend: false,
    },
    {
        id: "user-4",
        name: "PixelCraft",
        username: "@pixelcraft",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=PixelCraft",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=PixelCraft",
        bio: "Builder and explorer across indie & sandbox survival realms.",
        status: "online",
        isOnline: true,
        game: "Hollow Knight",
        favoriteGame: "Hollow Knight",
        isFriend: false,
    },
    {
        id: "user-5",
        name: "RanniTheWitch",
        username: "@ranni_witch",
        avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Ranni",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Ranni",
        bio: "Age of Stars enthusiast. Elden Ring lore theorist.",
        status: "online",
        isOnline: true,
        game: "ELDEN RING",
        favoriteGame: "ELDEN RING",
        badge: "FOUNDER",
        isFriend: false,
    }
];
