import { type NotificationItem } from "./types";

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
    {
        id: "notif-1",
        type: "like",
        title: "GamerX99 đã thích bài viết của bạn",
        message: "Chê Counter-Strike 2 hack nhiều quá, Valve tính làm gì đây? 😂",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=GamerX99",
        timestamp: "2 phút trước",
        isRead: false,
        link: "/post/1",
    },
    {
        id: "notif-2",
        type: "comment",
        title: "NeoCyber đã bình luận bài viết của bạn",
        message: "\"Cảm ơn bạn đã chia sẻ tips build thuyền trong Raft, cực kỳ hữu ích luôn!\"",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=NeoCyber",
        timestamp: "15 phút trước",
        isRead: false,
        link: "/post/2",
    },
    {
        id: "notif-3",
        type: "system",
        title: "Thông báo hệ thống từ Valve",
        message: "Counter-Strike 2 vừa phát hành bản cập nhật mới (Armory Patch). Vào xem ngay các thay đổi vũ khí và skin!",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Valve",
        timestamp: "1 giờ trước",
        isRead: false,
        link: "/game/counter-strike-2",
    },
    {
        id: "notif-4",
        type: "follow",
        title: "Shouko_Pro và 3 người khác đã bắt đầu theo dõi bạn",
        message: "Chào mừng những đồng đội mới tham gia cùng bạn trên cộng đồng IndieG!",
        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Shouko",
        timestamp: "3 giờ trước",
        isRead: true,
        link: "/community",
    },
    {
        id: "notif-5",
        type: "system",
        title: "Sự kiện cuối tuần: Red Dead Redemption 2",
        message: "Giảm giá đặc biệt và nhân đôi XP trong chế độ Red Dead Online tuần này.",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Rockstar",
        timestamp: "1 ngày trước",
        isRead: true,
        link: "/game/red-dead-redemption-2",
    },
];
