import { type NotificationItem } from "./types";

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
    {
        id: "notif-1",
        userId: "user-current",
        type: "like",
        referenceId: "post-1",
        title: "Lượt thích mới",
        message: "EldenLord_VN và 14 người khác đã thích bài viết của bạn trong Counter-Strike 2 Vietnam.",
        isRead: false,
        createdAt: "10 phút trước",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=EldenLord",
        link: "/post/post-1",
    },
    {
        id: "notif-2",
        userId: "user-current",
        type: "comment",
        referenceId: "post-1",
        title: "Bình luận mới",
        message: "ShadowHunter đã trả lời bài viết của bạn: 'Pha ném smoke Mirage chuẩn chỉ đấy bro, tối nay 5 stack rank Premier nhé!'",
        isRead: false,
        createdAt: "25 phút trước",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=ShadowHunter",
        link: "/post/post-1",
    },
    {
        id: "notif-3",
        userId: "user-current",
        type: "mention",
        referenceId: "post-2",
        title: "Nhắc đến bạn",
        message: "MonkeyKing_88 đã nhắc đến bạn trong một thảo luận: '@thehiep thử build Byakko Katana này xem, chém boss bao mượt!'",
        isRead: false,
        createdAt: "1 giờ trước",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=MonkeyKing",
        link: "/post/post-2",
    },
    {
        id: "notif-4",
        userId: "user-current",
        type: "community",
        referenceId: "cs2-vietnam",
        title: "Thông báo cộng đồng",
        message: "Counter-Strike 2 Vietnam vừa công bố giải đấu 'IndieG Premier Cup Season 4' với tổng giải thưởng 15.000.000 VNĐ.",
        isRead: true,
        createdAt: "3 giờ trước",
        avatarUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=CS2Vietnam",
        link: "/community/cs2-vietnam",
    },
    {
        id: "notif-5",
        userId: "user-current",
        type: "follow",
        referenceId: "user-3",
        title: "Người theo dõi mới",
        message: "CyberSamurai đã bắt đầu theo dõi bạn.",
        isRead: true,
        createdAt: "5 giờ trước",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=CyberSamurai",
        link: "/profile/@cybersamurai",
    },
    {
        id: "notif-6",
        userId: "user-current",
        type: "system",
        referenceId: "sys-achieve-1",
        title: "Thành tựu mới",
        message: "🎉 Chúc mừng bạn đã mở khóa huy hiệu 'Nhà Thám Hiểm' khi hoạt động tích cực trong 5 cộng đồng game!",
        isRead: true,
        createdAt: "1 ngày trước",
        avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=IndieGSystem",
        link: "/profile/me",
    },
];
