import avatarGame from "../../assets/logos/raft-logo.png";
import raftImg from "../../assets/logos/raft-logo.png";
import butterflyEmeraldImg from "../../assets/mock-data/butterfly-emarald.webp";
import dust2Img from "../../assets/bgs/cs2_bg.jpg";
import figuresImg from "../../assets/mock-data/figures.jpeg";
import type { PostData } from "./types";


export const ALL_POSTS: PostData[] = [
    {
        id: 1,
        author: "User123",
        authorAvatar: avatarGame,
        authorRank: "pro",
        gameTag: "Raft",
        timeAgo: "2 giờ trước",
        title: "Setup base ngoài khơi cực chill sau 40 ngày sinh tồn",
        content:
            "Cuối cùng cũng build xong base 3 tầng, có cả khu trồng trọt và bẫy cá tự động. " +
            "Ai đang chơi Raft chia sẻ layout của mọi người xem nào!",
        images: [raftImg, dust2Img],
        tags: ["📸 Showcase / Media", "Raft", "Basebuilding", "Survival"],
        likes: 24,
        comments: 8,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 2,
        author: "GhostRider",
        authorAvatar: avatarGame,
        authorRank: "rookie",
        gameTag: "Red Dead Redemption 2",
        timeAgo: "5 giờ trước",
        title: "Bản mod đồ hoạ 4K mới ra, chạy siêu mượt cho RDR2",
        content:
            "Vừa test bản mod textures mới cho RDR2, cải thiện chất lượng ánh sáng ban đêm " +
            "đáng kể mà FPS không giảm nhiều. Để link tải mod ở comment cho anh em.",
        tags: ["💡 Thảo Luận & Guide", "RDR2", "Mods", "Graphics"],
        likes: 56,
        comments: 19,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 3,
        author: "TacticalGamer",
        authorAvatar: avatarGame,
        authorRank: "master",
        gameTag: "Counter Strike 2",
        timeAgo: "1 ngày trước",
        title: "Tips aim training cho người mới lên Premier CS2",
        content:
            "Chia sẻ routine warm-up 15 phút mỗi ngày giúp mình cải thiện aim rõ rệt sau 2 tuần. " +
            "Không cần app ngoài, chỉ cần deathmatch đúng cách và tập control recoil.",
        images: [figuresImg, butterflyEmeraldImg, dust2Img],
        tags: ["💡 Thảo Luận & Guide", "CS2", "Tips", "Aim"],
        likes: 132,
        comments: 41,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 4,
        author: "NightOwl",
        authorAvatar: avatarGame,
        authorRank: "elite",
        gameTag: "Raft",
        timeAgo: "30 phút trước",
        title: "Tuyển 2 bạn chơi Raft chế độ Hardcore coop tối nay!",
        content:
            "Cả squad hiện có 2 người onl mỗi tối từ 20h, cần tìm thêm 2 anh em chung chí hướng xây dựng hạm đội trên biển. Không toxic, có mic discord nhé!",
        images: [raftImg, raftImg, raftImg],
        tags: ["🤝 Tìm Đồng Đội", "Raft", "Coop", "Squad"],
        likes: 89,
        comments: 27,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 5,
        author: "ProSniper",
        authorAvatar: avatarGame,
        authorRank: "legend",
        gameTag: "Counter Strike 2",
        timeAgo: "3 giờ trước",
        title: "AWP no-scope highlight reel — 20 kills in one match",
        content:
            "Vừa có một trận siêu đỉnh với AWP tại Inferno, chia sẻ clip highlight cho mọi người xem. " +
            "Tất cả đều là no-scope xử lý nhanh trong nháy mắt!",
        images: [butterflyEmeraldImg],
        tags: ["📸 Showcase / Media", "CS2", "Highlight", "AWP"],
        likes: 340,
        comments: 88,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 6,
        author: "MapMaker",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Counter Strike 2",
        timeAgo: "12 giờ trước",
        title: "🏆 Giải đấu CS2 Community Open Autumn 2026 — Đăng ký ngay!",
        content:
            "BQT mở đăng ký giải đấu cộng đồng CS2 cho các team amateur và bán chuyên. Tổng giải thưởng 50.000.000 VNĐ. Các đội trưởng vào đọc kỹ thể lệ thi đấu và đăng ký line-up trước ngày 15/08 nhé!",
        images: [dust2Img],
        tags: ["📢 Thông Báo & Event", "CS2", "Compe", "Tournament"],
        likes: 512,
        comments: 143,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
    {
        id: 7,
        author: "ViperKing",
        authorAvatar: avatarGame,
        authorRank: "pro",
        gameTag: "Valorant",
        timeAgo: "1 giờ trước",
        title: "Tìm 2 bạn chơi Controller/Initiator leo rank Ascendant tối nay",
        content:
            "Team hiện có 1 Duelist và 1 Sentinel, cần tìm 2 bạn call team tốt, không toxic, onl tầm 20h - 23h hàng ngày. Ai chơi để lại Riot ID hoặc discord add liền nha!",
        tags: ["🤝 Tìm Đồng Đội", "Valorant", "Ranked", "Ascendant"],
        likes: 45,
        comments: 18,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 8,
        author: "TarnishedOne",
        authorAvatar: avatarGame,
        authorRank: "rookie",
        gameTag: "Elden Ring",
        timeAgo: "4 giờ trước",
        title: "Xin hướng dẫn cách né combo của Promised Consort Radahn trong DLC?",
        content:
            "Mình đánh boss cuối DLC Shadow of the Erdtree đến phase 2 là bị clone chém không thấy đường né. Anh em đang dùng build khiên hay lăn né thế nào cho xin chút kinh nghiệm với!",
        tags: ["❓ Hỏi Đáp (Q&A)", "EldenRing", "BossFight", "DLC"],
        likes: 67,
        comments: 32,
        tab: "following",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 9,
        author: "CyberSamurai",
        authorAvatar: avatarGame,
        authorRank: "immortal",
        gameTag: "Cyberpunk 2077",
        timeAgo: "6 giờ trước",
        title: "Góc ảnh Night City lúc trời mưa với Path Tracing overdrive",
        content:
            "Chia sẻ bộ ảnh chụp bằng Photo Mode in-game tại quận Japantown và Afterlife. Đồ hoạ Cyberpunk 2077 kết hợp ray-tracing thực sự là một kiệt tác nghệ thuật!",
        tags: ["📸 Showcase / Media", "Cyberpunk", "Photography", "NightCity"],
        likes: 210,
        comments: 54,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 10,
        author: "SunWukong",
        authorAvatar: avatarGame,
        authorRank: "master",
        gameTag: "Black Myth: Wukong",
        timeAgo: "8 giờ trước",
        title: "Bí kíp hạ gục Nhị Lang Thần (Erlang Shen) không tốn bầu hồ lô",
        content:
            "Sử dụng Pháp Bảo Quạt Ba Tiêu kết hợp bộ giáp Tề Thiên để phá giáp siêu nhanh. Chi tiết chuỗi combo đòn đánh nặng và phân thân trong bài hướng dẫn này!",
        tags: ["💡 Thảo Luận & Guide", "Wukong", "Bosses", "Secret"],
        likes: 189,
        comments: 42,
        tab: "foryou",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 11,
        author: "LosSantosBro",
        authorAvatar: avatarGame,
        authorRank: "veteran",
        gameTag: "Grand Theft Auto V & Online",
        timeAgo: "3 giờ trước",
        title: "Tuyển anh em chạy Heist Cayo Perico & Casino chia đều 25% mỗi người",
        content:
            "Cần 3 đồng đội biết làm nhiệm vụ stealth, không bắn lung tung, đủ mic discord. Chuẩn bị bay vào việc luôn trong tối nay!",
        tags: ["🤝 Tìm Đồng Đội", "GTAV", "Heist", "FiveM"],
        likes: 72,
        comments: 29,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: false,
    },
    {
        id: 12,
        author: "RedstoneMaster",
        authorAvatar: avatarGame,
        authorRank: "grandmaster",
        gameTag: "Minecraft Builders & Redstone",
        timeAgo: "10 giờ trước",
        title: "Hoàn thành lâu đài phong cách Gothic 10.000 khối sau 2 tháng solo",
        content:
            "Sử dụng BSL Shaders cùng Conquest texture pack. Lâu đài có đầy đủ nội thất từ hầm ngục đến tháp chuông. Để lại link tải map world save cho mọi người tham quan!",
        tags: ["📸 Showcase / Media", "Minecraft", "MegaBuild", "Shader"],
        likes: 420,
        comments: 95,
        tab: "hot",
        privacy: "public",
        allowComments: true,
        pinned: true,
    },
];