import { type Squad, type SquadVoiceType } from "./types";

export const GAME_OPTIONS = [
    "Counter Strike 2",
    "Valorant",
    "League of Legends",
    "Dota 2",
    "Apex Legends",
    "PUBG",
    "Genshin Impact",
    "Minecraft",
    "Grand Theft Auto V",
    "Elden Ring",
    "Raft",
    "Red Dead Redemption 2",
    "Cyberpunk 2077",
    "Khác...",
];

export const GAME_FILTERS = [
    "all",
    ...GAME_OPTIONS.filter((g) => g !== "Khác..."),
];

export const QUICK_TAGS = [
    "🤝 Tìm Đồng Đội",
    "No Toxic",
    "Try Hard",
    "Chill",
    "Coop",
    "Ranked",
    "Hardcore",
    "Equal Pay",
    "Newbie Friendly",
    "Voice Required",
];

export const VOICE_OPTIONS: { value: SquadVoiceType; label: string }[] = [
    { value: "Discord Required", label: "🎧 Bắt buộc có Mic Discord" },
    { value: "In-game Voice", label: "🎙️ Voice chat trong game" },
    { value: "Optional", label: "👌 Có mic hay không đều được" },
    { value: "No Mic", label: "🔇 Chỉ chat text / No Mic" },
];

export const INITIAL_SQUADS: Squad[] = [
    {
        id: "squad-1",
        name: "Premier 20k+ Tryhard tìm Smoke & AWP player",
        game: "Counter Strike 2",
        description: "Cần tìm 1 AWP cứng và 1 Support biết ném set smoke Mirage/Inferno. Giao tiếp văn minh, tryhard leo 22k Elo.",
        tags: ["Try Hard", "Ranked", "Voice Required", "CS2"],
        currentMembers: 4,
        maxMembers: 5,
        voice: "Discord Required",
        isMySquad: false,
        roomCode: "#CS2-PREMIER-20K",
        discordUrl: "https://discord.gg/indieg-cs2",
        createdAt: "10 phút trước",
        status: "recruiting",
        members: [
            {
                id: "m-101",
                username: "ShadowHunter",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ShadowHunter",
                role: "Leader",
                status: "in-game",
                playtime: "Mirage 12-11",
            },
            {
                id: "m-102",
                username: "Viper_Aim",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Viper_Aim",
                role: "Member",
                status: "in-game",
                playtime: "Mirage 12-11",
            },
            {
                id: "m-103",
                username: "FlashKing",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=FlashKing",
                role: "Member",
                status: "in-game",
                playtime: "Mirage 12-11",
            },
            {
                id: "m-104",
                username: "BaiterPro",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=BaiterPro",
                role: "Member",
                status: "online",
            },
        ],
    },
    {
        id: "squad-2",
        name: "Leo Rank Kim Cương / Ascendant đêm nay",
        game: "Valorant",
        description: "Squad 3 người đang cần thêm 1 Initiator (Sova/Fade) và 1 Controller (Omen/Brim). No toxic, mic vui vẻ.",
        tags: ["Ranked", "No Toxic", "Voice Required"],
        currentMembers: 3,
        maxMembers: 5,
        voice: "Discord Required",
        isMySquad: false,
        roomCode: "#VAL-DIAMOND-VN",
        discordUrl: "https://discord.gg/indieg-val",
        createdAt: "25 phút trước",
        status: "recruiting",
        members: [
            {
                id: "m-201",
                username: "LunaStream",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=LunaStream",
                role: "Leader",
                status: "online",
            },
            {
                id: "m-202",
                username: "JettDiff",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=JettDiff",
                role: "Member",
                status: "online",
            },
            {
                id: "m-203",
                username: "ReynaSmurf",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ReynaSmurf",
                role: "Member",
                status: "online",
            },
        ],
    },
    {
        id: "squad-3",
        name: "Hỗ trợ Co-op diệt Consort Radahn DLC",
        game: "Elden Ring",
        description: "Đang kẹt ở Cổng Thần linh Belurat Gaol. Cần Tarnished kiên nhẫn build Fingerprint Shield hoặc Bleed phụ đánh boss.",
        tags: ["Coop", "Hardcore", "Chill"],
        currentMembers: 2,
        maxMembers: 3,
        voice: "Optional",
        isMySquad: false,
        roomCode: "#ELDEN-RADAHN-PASS",
        createdAt: "1 giờ trước",
        status: "recruiting",
        members: [
            {
                id: "m-301",
                username: "EldenLord_VN",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=EldenLord",
                role: "Leader",
                status: "in-game",
                playtime: "Belurat Gaol",
            },
            {
                id: "m-302",
                username: "LetMeSoloHim",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=LetMeSoloHim",
                role: "Member",
                status: "online",
            },
        ],
    },
    {
        id: "squad-4",
        name: "Server Sinh Tồn Hardcore Season 4 xây Megabase",
        game: "Minecraft",
        description: "Server Vanilla 1.21 whitelist riêng, tự động hóa farm redstone và xây đại kiến trúc fantasy. Chào đón anh em chăm chỉ.",
        tags: ["Chill", "Coop", "Newbie Friendly"],
        currentMembers: 5,
        maxMembers: 8,
        voice: "Optional",
        isMySquad: false,
        roomCode: "#MC-HARDCORE-S4",
        discordUrl: "https://discord.gg/indieg-mc",
        createdAt: "2 giờ trước",
        status: "recruiting",
        members: [
            {
                id: "m-401",
                username: "RedstoneArchitect",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=RedstoneArchitect",
                role: "Leader",
                status: "online",
            },
            {
                id: "m-402",
                username: "Miner_VN",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Miner_VN",
                role: "Member",
                status: "online",
            },
            {
                id: "m-403",
                username: "SteveTheBuilder",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=SteveTheBuilder",
                role: "Member",
                status: "online",
            },
            {
                id: "m-404",
                username: "NetherKnight",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=NetherKnight",
                role: "Member",
                status: "offline",
            },
            {
                id: "m-405",
                username: "DiamondHunter",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=DiamondHunter",
                role: "Member",
                status: "offline",
            },
        ],
    },
    {
        id: "squad-5",
        name: "Cayo Perico & Doomsday Heist chia 25% đều",
        game: "Grand Theft Auto V",
        description: "Điểm hẹn Submarine Kosatka chuẩn bị xong hết prep mission. Tìm đồng đội biết stealth chạy xe máy nhảy vách đá.",
        tags: ["Equal Pay", "Coop", "Try Hard"],
        currentMembers: 3,
        maxMembers: 4,
        voice: "In-game Voice",
        isMySquad: false,
        roomCode: "#GTA-CAYO-HEIST",
        createdAt: "3 giờ trước",
        status: "recruiting",
        members: [
            {
                id: "m-501",
                username: "LosSantosDrifter",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=LosSantosDrifter",
                role: "Leader",
                status: "online",
            },
            {
                id: "m-502",
                username: "PavelFanboy",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=PavelFanboy",
                role: "Member",
                status: "online",
            },
            {
                id: "m-503",
                username: "NightCityInfiltrator",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=NightCityInfiltrator",
                role: "Member",
                status: "online",
            },
        ],
    },
    {
        id: "squad-6",
        name: "Sinh tồn trên bè Raft Utopia Chapter 3",
        game: "Raft",
        description: "Bè 3 tầng đầy đủ động cơ và trạm nhiên liệu sinh học. Cần 1 bạn chuyên lái tàu và 1 bạn thích lặn biển nhặt tài nguyên.",
        tags: ["Chill", "Coop", "No Toxic"],
        currentMembers: 2,
        maxMembers: 4,
        voice: "Optional",
        isMySquad: false,
        roomCode: "#RAFT-UTOPIA-COOP",
        createdAt: "5 giờ trước",
        status: "recruiting",
        members: [
            {
                id: "m-601",
                username: "SailorSam",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=SailorSam",
                role: "Leader",
                status: "online",
            },
            {
                id: "m-602",
                username: "SharkHunter_VN",
                avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=SharkHunter_VN",
                role: "Member",
                status: "online",
            },
        ],
    },
];
