import type { FeaturedStory, NewsItem, EventItem, ViralMediaTile, TrendingTag } from "./types";
import { CS2_BANNER, RDR2_BANNER, CS2_SCREENSHOTS } from "@/shared/constants/images";

export const FEATURED_STORIES: FeaturedStory[] = [
    {
        id: "feat-1",
        title: "Counter-Strike 2: Đỉnh cao bắn súng chiến thuật trên Source 2",
        slug: "counter-strike-2",
        category: "FPS ESPORTS",
        genres: ["Action", "FPS", "Esports"],
        artworkUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/730/library_hero.jpg",
        description: "Bản nâng cấp toàn diện mang tính lịch sử với cơ chế khói tương tác sinh động và hệ thống sub-tick vượt trội.",
        activePlayers: "1.4M người chơi",
        rating: "4.8",
        communityName: "Counter-Strike 2 Vietnam",
        communityMembers: "34.5k",
    },
    {
        id: "feat-2",
        title: "Elden Ring: Shadow of the Erdtree - Bản mở rộng xuất sắc nhất năm",
        slug: "elden-ring",
        category: "ACTION RPG",
        genres: ["Souls-like", "RPG", "Open World"],
        artworkUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_hero.jpg",
        description: "Khám phá vùng đất Realm of Shadow đầy hiểm nguy cùng những trận chiến boss kinh điển làm say lòng game thủ toàn cầu.",
        activePlayers: "450k người chơi",
        rating: "4.9",
        communityName: "Elden Ring Vietnam",
        communityMembers: "28.9k",
    },
    {
        id: "feat-3",
        title: "Black Myth: Wukong: Cơn sốt huyền thoại Tây Du Ký khuynh đảo làng game",
        slug: "black-myth-wukong",
        category: "ACTION RPG",
        genres: ["Action", "RPG", "Souls-like"],
        artworkUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2358720/library_hero.jpg",
        description: "Hóa thân thành Người Được Chọn dấn thân vào hành trình vạn dặm khám phá chân tướng truyền thuyết Tây Du Ký trên đồ họa Unreal Engine 5 đỉnh cao.",
        activePlayers: "2.2M người chơi",
        rating: "4.8",
        communityName: "Black Myth: Wukong Vietnam",
        communityMembers: "42.3k",
    },
    {
        id: "feat-4",
        title: "Cyberpunk 2077: Phantom Liberty - Hồi sinh ngoạn mục của siêu phẩm Night City",
        slug: "cyberpunk-2077",
        category: "SCI-FI RPG",
        genres: ["RPG", "Action", "Open World"],
        artworkUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_hero.jpg",
        description: "Khám phá Dogtown đầy hiểm nguy cùng điệp viên Solomon Reed trong bản mở rộng đỉnh cao được đánh giá xuất sắc nhất CD PROJEKT RED.",
        activePlayers: "140k người chơi",
        rating: "4.7",
        communityName: "Cyberpunk 2077 Vietnam",
        communityMembers: "19.4k",
    },
];

export const VIETNAMESE_NEWS_ITEMS: NewsItem[] = [
    {
        id: "news-1",
        title: "Valve công bố giải đấu Major CS2 tiếp theo với tổng giải thưởng 1.25 triệu USD",
        developer: "Valve Corporation",
        genre: "Esports",
        status: "NÓNG HỔI",
        rating: "5.0",
        date: "Hôm nay, 14:30",
        description: "Giải đấu Major danh giá nhất mùa thu sẽ quy tụ 24 đội tuyển CS2 mạnh nhất thế giới tranh tài.",
        imageUrl: CS2_BANNER,
        linkSlug: "counter-strike-2",
        tags: ["CS2", "Major", "Esports"],
        isHighlight: true,
    },
    {
        id: "news-2",
        title: "Thần Trùng (The Death): Game kinh dị Việt Nam tạo dấu ấn đậm nét trên trường quốc tế",
        developer: "DUT Studio",
        genre: "Horror / Adventure",
        status: "ĐÃ RA MẮT",
        rating: "4.9",
        date: "Hôm qua",
        description: "Dự án gây ấn tượng mạnh với bối cảnh Hà Nội thập niên 90 tái hiện sống động không gian văn hóa dân gian tâm linh Việt Nam.",
        imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1726400/header.jpg",
        linkSlug: "counter-strike-2",
        tags: ["IndieVN", "Horror", "DUTStudio"],
        isHighlight: false,
    },
];

export const ONGOING_EVENTS: EventItem[] = [
    {
        id: "event-1",
        title: "Giải đấu CS2 Premier League Vietnam Mùa 1",
        subtitle: "Tranh tài 5v5 trực tiếp mỗi cuối tuần",
        date: "20 Tháng 10 - 05 Tháng 11",
        statusText: "Đang mở đăng ký",
        isLive: true,
        imageUrl: CS2_SCREENSHOTS[0],
        tags: ["CS2", "Tournament", "Premier"],
    },
    {
        id: "event-2",
        title: "Cuộc thi chụp ảnh Photo Mode - Miền Viễn Tây RDR2",
        subtitle: "Khoe tác phẩm nghệ thuật nhận quà Steam Wallet",
        date: "01 Tháng 10 - 15 Tháng 10",
        statusText: "Đang diễn ra",
        imageUrl: RDR2_BANNER,
        tags: ["RDR2", "Contest", "PhotoMode"],
    },
];

export const TRENDING_TAGS: TrendingTag[] = [
    { id: "tag-1", name: "CS2Clutch", count: "1.2k bài viết", isHot: true },
    { id: "tag-2", name: "EldenRingDLC", count: "890 bài viết", isHot: true },
    { id: "tag-3", name: "Cyberpunk2077", count: "540 bài viết", isHot: false },
    { id: "tag-4", name: "RaftCoop", count: "320 bài viết", isHot: false },
    { id: "tag-5", name: "IndieGameVN", count: "280 bài viết", isHot: true },
];

export const VIRAL_TILES: ViralMediaTile[] = [
    {
        id: "viral-1",
        author: "ShadowHunter",
        authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ShadowHunter",
        title: "Pha xử lý AWP vẩy tâm thần sầu round đấu match point",
        contentType: "SCREENSHOT",
        imageUrl: CS2_SCREENSHOTS[1],
        likes: "1.4k",
        commentsCount: "86",
        gameTag: "Counter-Strike 2",
    },
    {
        id: "viral-2",
        author: "EldenLord_VN",
        authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=EldenLord",
        title: "Khoảnh khắc hạ gục Malenia chỉ bằng nắm đấm tay không!",
        contentType: "SCREENSHOT",
        imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_943bf6fe62352757d9070c1d33e50b92fe8539f1.1920x1080.jpg",
        likes: "2.1k",
        commentsCount: "142",
        gameTag: "ELDEN RING",
    },
    {
        id: "viral-3",
        author: "CyberSamurai",
        authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=CyberSamurai",
        title: "Bộ ảnh chụp xe độ Rayfield Caliburn dưới mưa neon Night City",
        contentType: "SCREENSHOT",
        imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_2f649b68d579bf87011487d29bc4ccbfdd97d34f.1920x1080.jpg",
        likes: "890",
        commentsCount: "38",
        gameTag: "Cyberpunk 2077",
    },
    {
        id: "viral-4",
        author: "MonkeyKing_88",
        authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=MonkeyKing",
        title: "Tung chiêu Định Thân Pháp trảm sát boss Lãng Lý Bạch Điều",
        contentType: "SCREENSHOT",
        imageUrl: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/ss_86c4b7462bba219a0d0b89931a35812b9f188976.1920x1080.jpg",
        likes: "3.5k",
        commentsCount: "215",
        gameTag: "Black Myth: Wukong",
    },
    {
        id: "viral-5",
        author: "ArthurMorgan_VN",
        authorAvatar: "https://api.dicebear.com/7.x/bottts/svg?seed=ArthurMorgan",
        title: "Hoàng hôn buông trên rặng núi Grizzlies - Góc máy Photo Mode tuyệt đẹp",
        contentType: "SCREENSHOT",
        imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/ss_d1a8f5a69155c3186c65d1da90491fcfd43663d9.1920x1080.jpg",
        likes: "1.9k",
        commentsCount: "92",
        gameTag: "Red Dead Redemption 2",
    },
];
