/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSquadIndexRouteImport } from './routes/_layout/squad/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutCommunityIndexRouteImport } from './routes/_layout/community/index'
import { Route as LayoutBookmarkIndexRouteImport } from './routes/_layout/bookmark/index'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as LayoutProfileUserIdRouteImport } from './routes/_layout/profile/$userId'
import { Route as LayoutPostPostIdRouteImport } from './routes/_layout/post/$postId'
import { Route as LayoutGameGameSlugRouteImport } from './routes/_layout/game/$gameSlug'
import { Route as LayoutCommunityCommunityIdRouteImport } from './routes/_layout/community/$communityId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSquadIndexRoute = LayoutSquadIndexRouteImport.update({
  id: '/squad/',
  path: '/squad/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommunityIndexRoute = LayoutCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookmarkIndexRoute = LayoutBookmarkIndexRouteImport.update({
  id: '/bookmark/',
  path: '/bookmark/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LayoutProfileUserIdRoute = LayoutProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostPostIdRoute = LayoutPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGameGameSlugRoute = LayoutGameGameSlugRouteImport.update({
  id: '/game/$gameSlug',
  path: '/game/$gameSlug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommunityCommunityIdRoute =
  LayoutCommunityCommunityIdRouteImport.update({
    id: '/community/$communityId',
    path: '/community/$communityId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRoute
  '/community/$communityId': typeof LayoutCommunityCommunityIdRoute
  '/game/$gameSlug': typeof LayoutGameGameSlugRoute
  '/post/$postId': typeof LayoutPostPostIdRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/bookmark/': typeof LayoutBookmarkIndexRoute
  '/community/': typeof LayoutCommunityIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/squad/': typeof LayoutSquadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRoute
  '/community/$communityId': typeof LayoutCommunityCommunityIdRoute
  '/game/$gameSlug': typeof LayoutGameGameSlugRoute
  '/post/$postId': typeof LayoutPostPostIdRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/bookmark': typeof LayoutBookmarkIndexRoute
  '/community': typeof LayoutCommunityIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/squad': typeof LayoutSquadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/community/$communityId': typeof LayoutCommunityCommunityIdRoute
  '/_layout/game/$gameSlug': typeof LayoutGameGameSlugRoute
  '/_layout/post/$postId': typeof LayoutPostPostIdRoute
  '/_layout/profile/$userId': typeof LayoutProfileUserIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/_layout/bookmark/': typeof LayoutBookmarkIndexRoute
  '/_layout/community/': typeof LayoutCommunityIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/squad/': typeof LayoutSquadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community/$communityId'
    | '/game/$gameSlug'
    | '/post/$postId'
    | '/profile/$userId'
    | '/admin/'
    | '/developer/'
    | '/bookmark/'
    | '/community/'
    | '/profile/'
    | '/settings/'
    | '/squad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community/$communityId'
    | '/game/$gameSlug'
    | '/post/$postId'
    | '/profile/$userId'
    | '/admin'
    | '/developer'
    | '/bookmark'
    | '/community'
    | '/profile'
    | '/settings'
    | '/squad'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_layout'
    | '/auth'
    | '/_layout/'
    | '/_layout/community/$communityId'
    | '/_layout/game/$gameSlug'
    | '/_layout/post/$postId'
    | '/_layout/profile/$userId'
    | '/_authenticated/admin/'
    | '/_authenticated/developer/'
    | '/_layout/bookmark/'
    | '/_layout/community/'
    | '/_layout/profile/'
    | '/_layout/settings/'
    | '/_layout/squad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/squad/': {
      id: '/_layout/squad/'
      path: '/squad'
      fullPath: '/squad/'
      preLoaderRoute: typeof LayoutSquadIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/community/': {
      id: '/_layout/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof LayoutCommunityIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bookmark/': {
      id: '/_layout/bookmark/'
      path: '/bookmark'
      fullPath: '/bookmark/'
      preLoaderRoute: typeof LayoutBookmarkIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_layout/profile/$userId': {
      id: '/_layout/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProfileUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/post/$postId': {
      id: '/_layout/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof LayoutPostPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game/$gameSlug': {
      id: '/_layout/game/$gameSlug'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof LayoutGameGameSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/community/$communityId': {
      id: '/_layout/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/community/$communityId'
      preLoaderRoute: typeof LayoutCommunityCommunityIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCommunityCommunityIdRoute: typeof LayoutCommunityCommunityIdRoute
  LayoutGameGameSlugRoute: typeof LayoutGameGameSlugRoute
  LayoutPostPostIdRoute: typeof LayoutPostPostIdRoute
  LayoutProfileUserIdRoute: typeof LayoutProfileUserIdRoute
  LayoutBookmarkIndexRoute: typeof LayoutBookmarkIndexRoute
  LayoutCommunityIndexRoute: typeof LayoutCommunityIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutSquadIndexRoute: typeof LayoutSquadIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCommunityCommunityIdRoute: LayoutCommunityCommunityIdRoute,
  LayoutGameGameSlugRoute: LayoutGameGameSlugRoute,
  LayoutPostPostIdRoute: LayoutPostPostIdRoute,
  LayoutProfileUserIdRoute: LayoutProfileUserIdRoute,
  LayoutBookmarkIndexRoute: LayoutBookmarkIndexRoute,
  LayoutCommunityIndexRoute: LayoutCommunityIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutSquadIndexRoute: LayoutSquadIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
